branch-defaults:
  master:
    environment: my-env
    group_suffix: null
global:
  application_name: eb
  branch: null
  default_ec2_keyname: rp30
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
