branch-defaults:
  default:
    environment: my-env
  master:
    environment: my-env
environment-defaults:
  my-env:
    branch: null
    repository: null
global:
  application_name: port
  branch: null
  default_ec2_keyname: terraform
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
